JuliaImages/Images.jl

README.md, appveyor.yml, deps/build.jl
I can squash these if you'd prefer.
Might be good to turn on a nightly build of this too like we did for HDF5, as long as the queue's not getting too long on your AppVeyor account.
Results should be at https://ci.appveyor.com/project/tkelman/images-jl/build/1.0.4, will see
=> Update Windows binary URL, enable AppVeyor

deps/build.jl
It looks like the proper URL for downloading ImageMagick on Windows has changed yet again. In an attempt to reduce the frequency of breakages, I've tried to parse the downloads page to extract the currently-valid URL. We'll see what AppVeyor does with this.
=> Parse the ImageMagick binaries page to extract URL

deps/build.jl
This allows issues like https://github.com/timholy/Images.jl/issues/240 to work with `Homebrew.jl`.
Contents of bin directory on OSX 10.10 with ImageMagick 6.8.9:
```
Magick++-config
Magick-config
MagickCore-config
MagickWand-config
Wand-config
animate
compare
composite
conjure
convert
display
identify
import
mogrify
montage
stream
```
=> Add Homebrew.jl/ImageMagick's bin directory to PATH

REQUIRE, doc/function_reference.md, src/Images.jl, src/edge.jl, test/edge.jl
Ref https://github.com/JuliaLang/julia/pull/10150
=> update to use new Graphics package

src/algorithms.jl, src/edge.jl, test/edge.jl
* ~~Used by magnitude, orientation functions~~
* ~~Added Image{Gray} tests to test/edge.jl~~
~~I believe these will work, but I've only tested on Julia v0.4 so far, and only on gray-scale images.~~
**Edit:** The best fix ended up being modifying the behavior of `imgradients` to strip out ColorValue information.
=> RFC: strip ColorType information in imgradients return type (fixes #263)

src/map.jl
Since JuliaLang/julia@6e06078e1ba8ef517a89518c632ca96c3a704464 I get:
LoadError: syntax: space not allowed after ":" used for quoting
This fixes it so the package loads, but there are still a lot of deprecation warnings.
=> Fix LoadError with latest Julia

src/io.jl, src/ioformats/OSXnative.jl, test/readstream.jl, test/runtests.jl
Part 1, from #279
-- imread(source,Images.OSXNative) works if either source is a filename, IOStream, or Array{Uint8,1}
If it looks ok, I'll work on Images.ImageMagick
=> Add support for reading from memory blobs and streams in OSX

src/algorithms.jl, test/algorithms.jl
Call to imresize() resulted in ERROR: imresize_julia! not defined
Bug introduced in f203853c5b8dafc2115a1a7ba29a31ceeda18892
Initially function imresize was named imresize_julia (see https://groups.google.com/forum/#!msg/julia-users/wG1g9C7S6Mg/zx9Pqntv1e0J) to compare different imresize approaches
=> Fixed ERROR: imresize_julia! not defined

src/ioformats/nrrd.jl
Hi Tim.
I noticed there was a problem with a previous PR. The problem is that line 295 in nrrd.jl was not working if UfixedBase is wrapped around another type, like Gray{}.
=> Fix nrrd write issue when eltype is Gray{UfixedBase{...}}

src/ioformats/OSXnative.jl
The warning was
```julia
WARNING: convert{T}(p::Type{Ptr{T}},a::Array) is deprecated, use convert(p,pointer(a)) instead.
```
However, it seems to me that using a pointer in the first place was probably unnecessary.  @rsrock, am I missing something?
=> Minor change to remove deprecation warning.

doc/function_reference.md, src/io.jl, test/io.jl
Current, `imwrite` clamps values before writing, so that images that contain (for example) negative values get truncated at 0. This commit changes the behavior to throw an error, as argued in #256.
This also adds a new `mapinfo(Clamp, img)` to allow users to obtain the earlier behavior.
@rsrock, IIUC I don't need to do anything special to have the github.io documentation update, right?
=> Don't clamp by default before writing (fixes #256)

test/core.jl, test/map.jl
Ironically, right after the switch to FactCheck, 0.4 changed the priority of `=>`.
=> Fix Travis FactCheck failures for new parsing of =>

src/algorithms.jl, test/algorithms.jl
I'm a little more iffy on whether we want to accumulate to a `Float32` (the alternative being convert to `Float32` for the test), but on balance this seems to be the right thing to do.
The FFT test failure is due to https://github.com/JuliaLang/julia/pull/12393 (and easily fixed).
=> Fix two test failures related to precision

src/ioformats/Imagine.jl
Due to the recent change in parsing of => , imread was failing to create properties dict.  Simple fix.
=> Fixed imread for new parsing of =>

src/io.jl, test/io.jl
The 3-line fix for #336. It's a step backwards from weaning us from ImageMagick, but I'm comfortable with this until I finish the Colors->FileIO transition.
=> De-register our PBM reader, fallback on ImageMagick (fixes #336)

src/Images.jl
may help with the RegistryKeyLookupFailed `CoderModulesPath' error?
=> disable precompilation on windows

src/io.jl, test/io.jl
Fixes #336. While using poorly-typed colormaps is a bad idea, the error was not helpful.
=> imwrite (ImageMagick): provide fallback for poorly-typed images

deps/build.jl
I'm in no way a BinDeps expert, but this allowed me to satisfy the build process for Images.jl on ubuntu 15.04 with julia-0.3.10.  The proliferation of version numbers in ubuntu package names is a bit confusing, given that 15.04 doesn't seem to provide any alternatives to libmagickwand-6.q16-2.  Maybe I'm just doing something wrong.
=> Add additional libmagickwand package name for ubuntu 15.04

src/algorithms.jl
Suddenly, on 0.3 `A-img` has been failing.
It's not obvious why it changed, or why it worked earlier.
=> Add other-order operations for AbstractArrays (fixes #344)

deps/build.jl, src/Images.jl, src/ioformats/libmagickwand.jl
Precompiled modules that use Images were getting this warning:
```
WARNING: eval from module LibMagick to RegisterMismatch:
Expr(:ccall, Expr(:tuple, :MagickWandGenesis, "/usr/lib/x86_64-linux-gnu/libMagickWand.so.5")::Any, :Void, Expr(:tuple)::Any)::Any
** incremental compilation may be broken for this module **
```
It seems to be a consequence of the conditional build logic. By moving this into the deps.jl file, we avoid the conditional logic.
=> Move MagickWandGenesis into the deps.jl file

src/io.jl, src/ioformats/libmagickwand.jl, test/io.jl
I came across issue #279 since I head the same problem so I implemented @timholy's suggested fix.  
The patch allows imread to accept an Array as well as String and IO - I'm not sure whether this is too general though, do you have any opinion on tightening it?
=> Allow imread(::Array, Images.ImageMagick) to read from array of bytes

src/core.jl
Workaround https://github.com/JuliaLang/julia/issues/13082.
Trying to partially fix #356.
=> Workaround upstream weak type inference

src/Images.jl
The deprecation warning of `uint8sc` points to `ufixed8sc`, but that is not exported yet.
=> add exports for ufixedsc and ufixed8sc

.travis.yml, appveyor.yml
Now that FileIO is registered and tagged, we shouldn't need these anymore.
=> Don't clone FileIO manually in CI scripts

src/core.jl
Inference is run before the inlining pass, so when inference runs on constructors of the form `T{ndims(A)}(...)`, it does't see the inlined constant; it just sees an Int.  The fix is to just use the type parameters directly.  I've added this as an additional constructor to make sure it doesn't break any existing code with very poorly typed arrays.
=> Improve type stability of Image constructor

src/map.jl, test/algorithms.jl, test/core.jl, test/map.jl
Fixes an occasional fail-to-fail issue (e.g., https://ci.appveyor.com/project/timholy/images-jl/build/1.0.424/job/kinjj8svl0dxf3gp, https://github.com/JuliaLang/julia/pull/13834#issuecomment-152822134). CC @tkelman. Also tests that #356 really is fixed now thanks to #393. CC @cdsousa, @mbauman.
=> Testing fixes

.travis.yml, appveyor.yml, doc/function_reference.md, src/Images.jl, src/algorithms.jl, src/connected.jl, src/core.jl, src/edge.jl, src/map.jl, src/overlays.jl
```
julia> using Images
help?> separate
search: separate
imgs = separate(img) separates the color channels of img, for example returning an m-by-n-by-3 array from an m-by-n array of RGB.
```
This is a WIP because there are still many files to go, but I wanted to post this here now because of one concern: presumably it would be best to generate the [function reference](http://timholy.github.io/Images.jl/function_reference.html) from the docstrings. I haven't plumbed into the guts of the new documentation system, so: does anyone know how to do this?
Particular CC to @rsrock, since he invested a lot in the github.io docs.
=> Docstrings!

.travis.yml, appveyor.yml, test/core.jl
This is the bare minimum change to make the tests pass. I think there shouldn't be much (any?) others that needs updating given `Images` mostly delegate to the base version for indexing.
=> Fix tests for scalar index change on 0.5

doc/function_reference.md, src/Images.jl, src/algorithms.jl, test/algorithms.jl
In continuation with discussion from #402 
1. Added morphological tophat, bothat, gradient, laplacian functions
2. Basic test cases
3. Docs
I'm quite not sure if I've made proper/any use of copy, array properties to save memory or other optimizations for these functions. I thought, I'll push this is up and take feedback for the modifications/improvements if any needed. And, the documentation for these is a bit rusty too.
=> ENH: Add morphological tophat, bothat, gradient, laplacian

src/core.jl
A very tiny change to fix the following warning...
```WARNING: [a] concatenation is deprecated; use collect(a) instead
in depwarn at deprecated.jl:73
in oldstyle_vcat_warning at ./abstractarray.jl:29
in ctranspose at /home/hofmann/.julia/v0.4/Images/src/core.jl:1300```
=> Fixed deprecation warning

src/Images.jl
On 0.5.0-dev+3012 (commit 93cb2ae), Images.jl fails to load without importing Base.take into the module. This shouldn't break anything on v0.4.0+, but Base.take doesn't exist in v0.3 (at least according to the documentation here: http://docs.julialang.org/en/release-0.3/search/?q=Base.take&check_keywords=yes&area=default), so protecting against a failure there, as well.
Best,
Rob
=> Fix import (Base.take) error on v0.5-devel

src/algorithms.jl
This makes the documentation correspond to the code: `m` is taken to the power too.
Since I wasn't sure whether the comment or the code was right, I tried to find a reference for this formula, but my google-fu fails me. Is there a reference? If you link it, I could add it to this PR before merge.
=> Minor doc fix for `imstretch`.

src/core.jl, test/core.jl
In the course of considering #458, I noticed some missing methods and errors in converting to grayscale. I took the opportunity to rebase some of the conversion methods on `ccolor` from ColorTypes; this greatly simplifies the selection of a concrete color type. (There are probably more places where this could be leveraged.)
=> Fix some conversion bugs & rebase on ccolor

src/Images.jl, src/algorithms.jl, test/algorithms.jl
Allows `Base.flipdim` to be called with a string parameter denoting the dimension. Tests are included
For example, the following code flips the x dimension, independent of the storage order:
```julia
img = grayimg(UInt8[200 150; 50 1])
img2 = flipdim(img, "x")
```
Alternatively, additional shortcut functions are provided for the three most common spatial dimensions x, y, and z. These shortcut functions are called `flipx`, `flipy`, and `flipz` respectively.
For example, the following code is equivalent to the example provided above:
```julia
img = grayimg(UInt8[200 150; 50 1])
img2 = flipx(img)
```
=> Add flipdim with dimension as string parameter

src/map.jl, test/map.jl
Integer-valued images are not generally recommended (deciding contrast is a mess), but it's worth having them work. Note this also improves overflow-safety (for `From<:Signed`).
=> Support ScaleMinMax for To<:Integer

docs/src/function_reference.md, src/Images.jl, src/algorithms.jl, test/algorithms.jl
@timholy I found your version to be better than what I had earlier. Just one doubt : As you said, the two extra bins will create an issue for the histeq function. I could hard code that function to ignore those two bins but I dont know if that would be the correct way to do this. I do not want to remove the two a bins too since it gives a very nice representation of the image if (minval, maxval) does not cover the entire range. I feel we can do this : Take a (minval, maxval) range for the histeq function as well and then equalise only in that range. The default will be the entire range. This way we can have both the things. Does this look fine?
=> Adds Histogram Function

src/core.jl
=> Use deepcopy for dictcopy on julia-0.5

src/core.jl
See #484 
basically, for vectors it still prints Strings using `print` while using `showcompact` for other types
=> Use showcompact instead of print for metadata

REQUIRE, src/Images.jl, src/algorithms.jl, src/overlays.jl, test/algorithms.jl, test/overlays.jl
This makes subtle changes in how the histogram is computed. The key change is to clarify the meaning of the return values (see the changes to the docstring for a description), which necessitated changing some of the tests. While I understand that some of the return values may be worse from a DWIM perspective, from a mathematical standpoint this is more consistent.
Incidentally this fixes #490, and also some other problems on julia-0.5. It won't pass tests, however, until https://github.com/JuliaStats/StatsBase.jl/pull/166 is merged and tagged.
=> Fix histogram deprecation and behavior

docs/src/function_reference.md, src/Images.jl, src/algorithms.jl
This commit adds a histogram function to help with histogram equalisation.
=> Histogram Equalisation

src/Images.jl
Tests were failing because of the removal of julia-0.4 deprecations.
=> Fix float32/float64 import

src/core.jl, test/core.jl
=> Delete "colorspace" property when converting to Image{Gray}. Fixes #497.

src/algorithms.jl
- Changed dtype argument
- Fixed #503 
- Fixed #502 
Some unsolved issues : 
- #504 
- #503 (The convert(Array{GrayA}, img) method is not working. The returned datatype for transaparent images is ```Array{Any}``` instead of ```Array{Gray}```. This causes an error while saving the image.)
```julia
julia> img = testimage("house")
GrayA Images.Image with:
data: 512×512 Array{ColorTypes.GrayA{FixedPointNumbers.UFixed{UInt8,8}},2}
properties:
colorspace: Gray
spatialorder:  x y
julia> h=Images.histeq(img, 1000)
Gray Images.Image with:
data: 512×512 Array{Any,2}
properties:
colorspace: Gray
spatialorder:  x y
julia> save("test.jpg", h)
WARNING: MethodError(ImageMagick.mapinfo,(
Gray Images.Image with:
data: 512×512 Array{Any,2}
properties:
colorspace: Gray
spatialorder:  x y,))
in save_ at …
```
=> Fixes Issues with Histeq, changes the dtype argument.

src/Images.jl, src/core.jl, src/writemime.jl, test/writemime.jl
Once we drop 0.4 support, there should be some more internal renaming, but this is fine for now.
=> Fix writemime deprecation

src/algorithms.jl, test/algorithms.jl
Build fails on 0.4 because zero(YCbCr) is not found. Is ColorTypes not available for 0.4?
=> Adds Tests for Histeq

src/algorithms.jl, test/algorithms.jl
Was converting pixels of type ```Gray{U8}``` to Gray{Float64}``` on division, causing problems in direction coded LBP.
=> Fix Bilinear Interpolation

src/corner.jl, test/corner.jl
Since we went with a boolean return for ```fastcorners```, it seems better to have the same for ```imcorner``` as well. Also, finding corners using maxima is easier to use.
=> Adds Corner Peaks, Changes return type to Boolean

REQUIRE, src/algorithms.jl, src/core.jl, src/edge.jl, src/exposure.jl, test/algorithms.jl, test/edge.jl, test/map.jl
All tests passes locally. The WIP is because there's [one test](https://github.com/timholy/Images.jl/compare/yyc/0.6-dep?expand=1#diff-efda1537dfa19ffae4976ef9a6bf697cL33) that I need to change. The test starts to fail on 0.4 half way when I'm making the changes and I have no idea why it's happening.
=> Fix depwarn on 0.6 due to vectorized functions

NEWS.md, src/Images.jl, src/algorithms.jl, test/algorithms.jl, test/old/algorithms.jl, test/runtests.jl
At the moment, julia-0.6 is picky about what can and can't be in a `@generated` function, and `findlocalextrema` seems not to meet these requirements. As a consequence our tests have been failing on `nightly` for some time (e.g., https://travis-ci.org/timholy/Images.jl/builds/168159481).
I've gotten rid of a lot of the `@generated` functions in the `images-next` branch, and this PR (against that branch, not master) removes the last one, `findlocalextrema`. As a bonus, it's about 30-fold faster in my hands (I'm not quite sure why, the old version looked mostly OK, though if I had to guess the `in(d,region) ? x : y` test was to blame).
I also restructured `blob_LoG` according to the discussion in #546, and even made the output its own type. This is obviously a breaking change, but since the …
=> Rework interface to blob_LoG and reimplement findlocalextrema

src/algorithms.jl
Because it confused the syntax highlighting in Atom.
=> change a few backticks in docstrings

src/Images.jl, src/algorithms.jl, src/connected.jl, test/algorithms.jl, test/core.jl, test/edge.jl, test/map.jl, test/overlays.jl, test/runtests.jl
This fixes all of the test errors and most of the depwarns on master. Passing tests on master requires https://github.com/JuliaIO/FileIO.jl/pull/94 and some depwarns are fixed by https://github.com/JuliaArchive/FactCheck.jl/pull/80
The depwarns that are not fixed are:
* Extending `.+`, `.==` etc
Might need `@compat` support and might also need to decide what's the expected return type with loop fusion
* `@test_approx_eq`
It seems to behave differently wrt `NaN`?
* `reduce_dims`
Might want to go to `Compat.jl`
=> Fix 0.6 depwarns

src/distances.jl
Those moments in which you revisit code you have written and don't understand why you did what you did. This patch cleans up unnecessary memory allocation and puts a little bit more work in the processor.
I used `BenchmarkTools.jl` to compare implementations, there is a noticeable speedup. Can you please review and merge?
=> Save up memory in hausdorff distance

REQUIRE
Why is Zlib on the REQUIRE file? I cannot find it in `src/`
=> Remove Zlib from REQUIRE file

src/Images.jl, src/bwdist.jl, test/bwdist.jl, test/runtests.jl
This revamps #576, which revamps #99. While I was reluctant to wade into this, given that two people (@wkearn and @muhlba91) have both put significant effort into this, I decided I could no longer avoid respecting their heroism. To make sure everyone got due credit, I first rebased #99 on master (assigning credit to @wkearn), then "replayed" #576 on top of that (assigning credit to @muhlba91), and then added my own tweaks.
I almost merged #576 directly (after resolving the merge conflicts), but after profiling it and discovering that indeed `ind2sub` accounted for most of the runtime, I couldn't resist investigating. More importantly, I decided that a return type of `Array{CartesianIndex}` might be more useful to users than `Array{Int}` (where users would have to call `ind2sub` on the …
=> Another implementation of bwdist (feature_transform/euclidean_distance_transform)

REQUIRE, src/Images.jl, src/algorithms.jl, src/map-deprecated.jl, test/algorithms.jl
**NOT MERGE READY**
The branch corresponding to the move of `restrict` and `imresize` to ImageTransformations.jl.
This depends on ImageTransformations.jl being registered in METADATA.
see: https://github.com/JuliaImages/ImageTransformations.jl/pull/4
=> WIP: Move restrict and imresize to ImageTransformations

src/Images.jl, src/convexhull.jl, test/algorithms.jl, test/runtests.jl
The method convexhull computes the convex hull of a binary image using Graham scan algorithm. The method can return either the boundary of the convex hull or the filled out convex hull. I have also added some tests for convexhull.
=> added convex hull algorithm

src/edge.jl, test/edge.jl
As canny will return a binary image, an `Array{Bool}` would be more memory efficient than `Array{Float64}`.
=> Changed return type of canny

src/algorithms.jl, test/algorithms.jl
According to wikipedia:
* `n_scales = 0`: level-0(original image)
* `n_scales = 1` : level-1(1/2 resolution)
* …
=> Fix `n_scales` condition in `gaussian_pyramid`

src/showmime.jl, test/writemime.jl
Resolves #623 (after this change, `[zeros(Gray, 1)]` does not invoke any Images.jl-specific display code and therefore does not cause an error). We can still display an arbitrary-dimensional array of images, but each of those images must be a matrix, not an array.
=> only invoke HTML table display code for an array of colorant matrices

src/showmime.jl
Fixes #625 (assuming that that is, in fact, an error). 
Before:
After:
My reasoning is that this is more consistent with the way arrays are printed as text in Julia:
```julia
[fill(z * z2) for x in 1:2, y in 1:2, z in [0.5, 1], z2 in [0.5, 1]]
```
gives:
```
2×2×2×2 Array{Array{Float64,0},4}:
[:, :, 1, 1] =
0.25  0.25
0.25  0.25
[:, :, 2, 1] =
0.5  0.5
0.5  0.5
[:, :, 1, 2] =
0.5  0.5
0.5  0.5
[:, :, 2, 2] =
1.0  1.0
1.0  1.0
```
=> iterate over last dimension when grouping N-D tables of images

.travis.yml, REQUIRE, src/algorithms.jl, src/showmime.jl, test/algorithms.jl, test/old/algorithms.jl, test/old/core.jl, test/writemime.jl
See issue #628. Unfortunately `restrict(A, Axis{:name})` is no longer inferrable, and I've not found a way to fix this within Images. Fixing this will require a stand-alone demonstration reported to base julia.
This is presumably a consequence of other generalizations to `restrict`. On balance, I'd rather have support for arbitrary indices, and use a function barrier to resolve type instability problems.
fixes #624. However I had to disable some failing tests, CC @rdeits.
Deletes tests whose behavior was changed by https://github.com/JuliaImages/ImageCore.jl/pull/34
=> Fix various test failures

test/writemime.jl
Testing `show()` is somewhat useless, since the whole point of #623 was to prevent any Images.jl code from being called in the first place. This just provides a direct test against the old behavior sneaking back in.
=> more specific test for #623

NEWS.md, src/corner.jl, src/deprecated.jl, src/edge.jl, src/exposure.jl, test/corner.jl, test/edge.jl
After #607 (merged as #616), `canny` disambiguated its threshold using the new `Percentile` type. Before making a new release, for consistency we should get rid of all functions that use an argument corresponding to a `percentile::Bool`. The only other one I'm aware of is `imcorner`.
As a matter of principle, when adding deprecation warnings it's probably a good idea to deprecate anything else related that seems to need changing; this is a kindness to users, to prevent too much API churn. Therefore, I decided to make the `method` keyword argument a positional one. Julia can't dispatch on keyword arguments, so the result wouldn't be type-stable. That's not always important, but it also no longer seems very Julian to me to do this by a keyword argument. The new API supports the following …
=> Expunge `percentile` and `method` as (keyword) arguments from Images API

src/Images.jl, src/algorithms.jl
As discussed in https://github.com/JuliaImages/ImageMorphology.jl/issues/1
I will remove the definitions from ImageMorphology.jl after they are merged here.
=> Extend dilate/erode for ImageMeta

src/connected.jl, test/algorithms.jl
As discussed in https://github.com/JuliaImages/Images.jl/issues/677#issuecomment-344284124 .
- makes the function type stable
- about 4x speed improvement on the example discussed in the link above
=> improve component_centroids performance

REQUIRE, src/Images.jl, src/corner.jl, test/corner.jl
Introduces the function imcorner_subpixel as well as several requisite
support functions to facilitate the ability to detect corners to
sub-pixel precision.
The imcorner_subpixel uses the existing imcorner functionality to obtain
initial corner response values and a binary corner indicator matrix. The
corner response values and the indicator matrix are used in a univariate
quadratic interpolation scheme to determine the corner coordinates to
sub-pixel precision.
The new imcorner_subpixel function returns a length-3 NTuple of type
HomogeneousPoint2D, which represents the homogeneous coordinates of a
planar point.
=> Add sub-pixel corner detection capability #682

src/exposure.jl, test/exposure.jl
This is one attempt to improve the situation outlined in #690 
I have to admit I am not super happy about this either. That said, I do think we should not let `complement(::Array)` silently return something strange.
=> make complement signature more strict. fix #690

src/showmime.jl
Before 
After:
@alanedelman suggested the parenthetic in the vector display:
=> fix order of dimensions when showing an array of images

src/exposure.jl, test/exposure.jl
Fixes #686 
Calling `indices(img)` on a canonical array returns a tuple of type `Base.OneTo`. Unfortunately, there is currently no `fill` method defined in `Base` which can take a tuple of `Base.OneTo` as its dimension argument. Hence, I had to explicitly convert the tuple of `Base.OneTo` to a tuple of integers.
=> Fixes adjust_gamma so that it works on offset arrays 

src/algorithms.jl
For downsample <= 1, images are instead upscaled; Gaussian filtering serves no purpose in such instances.
=> Add gaussian_pyramid downsampling domain warning

.travis.yml, REQUIRE, appveyor.yml, docs/src/core.md, src/Images.jl, src/algorithms.jl, src/bwdist.jl, src/connected.jl, src/convexhull.jl, src/corner.jl, src/edge.jl, src/exposure.jl, src/juno.jl, src/labeledarrays.jl, src/showmime.jl, test/algorithms.jl, test/arrays.jl, test/bwdist.jl, test/corner.jl, test/deprecated.jl, test/edge.jl, test/exposure.jl, test/runtests.jl, test/writemime.jl
This depends on updates in some dependencies (notably ImageTransformations and ImageFiltering, along with their dependencies) for which PRs are pending at this time.
The vast majority of locally-caused deprecations are eliminated here.
With a set of bleeding-edge dependencies I am getting ~~4~~ ~~2~~ no errors and ~6~ no broken tests out of the test suite (except 4 tests needing fixes for ImageAxes; they are suppressed here).
The broken tests ~are~ were associated with `yen_threshold` which I have ~not studied~ apparently fixed.
2 errors ~~are~~ were associated with obsolete broadcast usage related to the `sumfinite!` function in `algorithms.jl`; ~~advice~~ review would be welcome.
~~The other 2 errors are in restriction and convex hull tests; I don't understand them yet.~~ Edit: fixed
=> update for Julia v0.7

REQUIRE, src/Images.jl
This PR fixes issue #731 
It depends on:
- https://github.com/JuliaGraphics/ColorTypes.jl/pull/111
- https://github.com/JuliaGraphics/Colors.jl/pull/320
=> Eliminate duplicate types already defined in ColorTypes.jl

test/REQUIRE
This was breaking tests on 1.0 and higher.
=> Remove FactCheck from test/REQUIRE

src/Images.jl, src/exposure.jl, test/exposure.jl
In contrast to `imhist` the `build_histogram` function will return the number of bins that the user requested.  
Furthermore, when working with an 8-bit image the `build_histogram` function will return the same bin boundaries whether the intensities are represented with a `FixedPointNumbers` (`N0f8`) in the interval [0,1] or by unsigned integers in the interval [0,255]. 
The histogram `counts` are returned as an `OffsetArray` and the **zero** index of  `counts` now stores the number of intensities that are less than the first bin boundary. This constitutes a breaking change from `imhist` which did not utilise an `OffsetArray`, and instead utilised the **first** index of `counts` to store the number of intensities that were less than the first bin boundary.
The choice of the name …
=> Adds `build_histogram` to address limitations of `imhist`

src/Images.jl, src/exposure.jl, test/exposure.jl
Removed the dependence on `searchsortedlast` from `build_histogram` to improve the performance of histogram construction. Added a fresh implementation of histogram equalization which  does not require `_histeq_pixel_rescale`.
=> Adds `adjust_histogram(Equalization(),...)`

src/algorithms.jl, test/algorithms.jl
This may seem like a bit of a rareified combination, but if you're running ImageFiltering 0.5.3+ and OffsetArrays 0.10.0+, you can trigger it on Images master with
```julia
using Images, TestImages
img = centered(testimage("mri"))
restrict(img)
```
I'm a bit unhappy about the implementation of `ofaxes` (it basically only supports Base and OffsetArrays), but I don't have a better idea ATM.
=> Fix `restrict` on an AxisArray with non-1 axes

src/algorithms.jl, test/algorithms.jl
fixes https://github.com/JuliaImages/Images.jl/issues/796
`dilate!` and `erode!` are not exported by `ImageMorphology`, and they're called without `using`
https://github.com/JuliaImages/Images.jl/blob/4cc66f9023973b8b0f2165f9738f02f20c378de0/src/algorithms.jl#L653-L654
=> add missing ImageMorphology import (fixes #796)

.travis.yml, appveyor.yml
According to discussion in https://github.com/JuliaImages/ImageCore.jl/pull/71#discussion_r277172826, when we drop the CI test on 0.7 we should drop the compatibility as well.
Since there's already a register PR: https://github.com/JuliaRegistries/General/pull/162, we can keep this version `0.18.0` still compatible with julia `v0.7`. And drop `v0.7` compatibility in the next minor version.
=> revert CI version to keep julia 0.7 compatible

src/Images.jl, src/algorithms.jl
These array operations are already deprecated, e.g., using `red.(img)` instead of `red(img)`
Actually, with the usage of `Array(T, size(img))` being invalid, these functions are broken but are not caught by any test cases. So deleting them without depwarn is quite safe.
=> remove array operation red,greed,blue

src/exposure.jl
Converting each element to `real` makes the `searchsortedlast` call dispatch on the faster method specialized for ranges.
Benchmarks:
```
using BenchmarkTools
using TestImages
img = testimage("lighthouse")
img_gray = Gray.(img)
img_normed = real.(img)
img_float = float.(img_normed)
```
Before:
```
@btime imhist($img)           # 24.367 ms (5 allocations: 386.06 KiB)
@btime imhist($img_gray)      # 23.378 ms (3 allocations: 1.92 KiB)
@btime imhist($img_normed)    # 12.228 ms (3 allocations: 1.92 KiB)
@btime imhist($img_float)     # 14.518 ms (3 allocations: 1.92 KiB)
```
After:
```
@btime imhist($img)           # 14.108 ms (5 allocations: 386.06 KiB)
@btime imhist($img_gray)      # 12.681 ms (3 allocations: 1.92 KiB)
@btime imhist($img_normed)    # 12.379 ms (3 allocations: 1.92 KiB) …
```
=> Faster imhist

src/Images.jl, test/exposure.jl
The reexported symbols from `ImageContrastAdjustment.jl` were not visible because I introduced new definitions (e.g. `adjust_histogram`) in `deprecations.jl` without an appropriate import (e.g. `import ImageContrastAdjustment: adjust_histogram`).  This meant that the API was not actually callable, as reported here: https://github.com/JuliaImages/Images.jl/pull/865#issuecomment-583209083
=> Ensures exported symbols  from ImageContrastAdjustment.jl are callable

src/Images.jl
Since ImageQualityIndexes v0.1.4:
* `psnr` -> `assess_psnr`
* `ssim` -> `assess_ssim`
Ref: https://github.com/JuliaImages/ImageQualityIndexes.jl/pull/15
=> add deprecation binds to ssim and psnr

Project.toml, src/Images.jl, src/algorithms.jl, src/compat.jl, src/deprecations.jl, test/algorithms.jl, test/runtests.jl
This PR actually consists of four independent changes (If needed, I could rebase it into four commits...)
* deprecate `Images.shepp_logan` in favor of `TestImages.shepp_logan`
* `one(::CartesianIndex)` -> `oneunit`
* suppress the noisy deprecation output; we only need to make sure it runs and test passes
* `QuartzImageIO` is removed as test dependency; it's more reliable to use only one IO backend
It's worth noting that there is a name conflict between `TestImages.shepp_logan` and `Images.shepp_logan`. The only solution to this that I can come up with is to reexport `TestImages.shepp_logan`.
=> [deprecation] shepp_logan and one(::CartesionIndex)

src/Images.jl, test/algorithms.jl
Currently tests are failing; it turns out that deprecations aren't re-exported automatically. This does it manually.
The absence of reports about this does suggest that most people seem to have figured this out on their own, but it is a little troubling.
=> Reexport the deprecated permuteddimsview

test/arrays.jl
Have added tests for different dimensions of arrays, the only type present was for 2 by 2 matrix,so i added tests for a 2 by 3 matrix.
=> added some more tests to arrays.jl

src/Images.jl
Minimum package version is 1.3 so this is no longer necessary as it is the default
=> Remove __precompile__ check

src/labeledarrays.jl, test/arrays.jl
`MappedArray` provides a more generic version of `ColorizedArray` so I believe it is good to not maintain `ColorizedArray` anymore.
`LazyArray` also provides similar operation; `LazyArray(@~ @. I * indexed_img)`.
closes https://github.com/JuliaImages/juliaimages.github.io/issues/132
=> deprecate ColorizedArray in favor of MappedArray

src/Images.jl
I deliberately separate this into a new PR so we don't get lost in the lengthy discussions in #971 
closes #982
=> rewrite the module docstring

Project.toml
The first version that is compatible to ImageCore v0.9
sit tight 🚀
=> Images v0.25.0

Project.toml
Given https://github.com/JuliaImages/Images.jl/pull/993 has been merged it would be good to get a new patch release to free up the ecosystem for the new ImageIO version.
As an aside, I think we've tagged a couple of non-breaking releases as breaking releases for ImageIO.
I think the rationale we've had has been that it makes sense when adding new backends, but I think it's not strictly a breaking change and causes downstream noise (like this)
=> Images v0.25.1

Project.toml, src/Images.jl
I realize that we don't need to load EllipsisNotation at all because IntegralArrays already does this:
https://github.com/JuliaImages/IntegralArrays.jl/blob/0f8bdfd7466504f789ee20935999598b79ca0e7e/src/IntegralArrays.jl#L7-L8
This is a bug fix for IntergralArrays v0.1.4, I've checked that this works for old IntergralArrays version v0.1.3. Fixes #1005.
Will merge and tag a new release once the test passes.
=> Images v0.25.2: remove EllipsisNotation

CONTRIBUTING.md, src/deprecations.jl
This also updates a few stale items or reorders tips for greater clarity.
=> Add release procedure in CONTRIBUTING
