JuliaImages/Images.jl

appveyor.yml, src/core.jl, src/io.jl, src/ioformats/libmagickwand.jl, src/ioformats/nrrd.jl, test/core.jl, test/runtests.jl
This should fix https://github.com/timholy/Images.jl/pull/242#issuecomment-68817935. CC @tkelman.
=> imread: always use an even # of bits for ImageMagick

src/io.jl, src/ioformats/libmagickwand.jl, test/readnrrd.jl
this allows installing in a non-default location
ref https://github.com/JuliaLang/julia/issues/8679#issuecomment-75796502
=> Use relative paths instead of Pkg.dir("Images")

src/algorithms.jl, src/colortypes.jl, test/io.jl, test/readnrrd.jl, test/readremote.jl, test/restrict.jl
This might fix the AppVeyor error in #259.
=> Don't redefine test directory-name variables

src/io.jl, src/ioformats/nrrd.jl
This is a working prototype that required minimal changes in the code, improves #273
=> imread() now supports mmap argument

doc/extendingIO.md, src/algorithms.jl, src/connected.jl, src/core.jl, src/ioformats/OSXnative.jl, src/ioformats/SIF.jl, src/overlays.jl, test/map.jl
Unit tests pass on OSX on 0.3 and 0.4 master
=> fixes for Tuple type

doc/core.md, doc/function_reference.md, src/Images.jl, src/core.jl, test/core.jl
This adds the raw(img) functionality, as discussed in #190
=> Added raw(img) to wrap the data out of UfixedBase, #190

src/algorithms.jl, src/core.jl, src/ioformats/Imagine.jl, src/overlays.jl
=> Fix some warnings on 0.4

REQUIRE, src/colortypes.jl
See https://github.com/JuliaLang/Color.jl/commit/c7cf2fce8e454fd20fa7ff4f7f7b7f41b713de3e
=> Update usage of makeshow for precompilation

test/io.jl, test/readremote.jl
=> make the reading from a stream test unix_only

README.md
Also a nice chance to see if we're green across the board.
=> Expand the credits

deps/build.jl
=> Make regexp non-greedy.

test/readremote.jl
It fixes only https://github.com/timholy/Images.jl/issues/344#issuecomment-134705453.
=> Update for changes in FactCheck (fixes #344)

src/Images.jl, src/writemime.jl, test/runtests.jl, test/writemime.jl
goes along with JuliaIO/ImageMagick.jl#10
=> move writemime to Images

src/algorithms.jl
Removes Pkg.test deprecation warning.
=> modified:   src/algorithms.jl:328 sumsq->abs2

src/Images.jl, src/algorithms.jl, test/algorithms.jl
=> Add @test_approx_eq_sigma_eps for approximate image testing

.travis.yml, README.md, REQUIRE, appveyor.yml, doc/function_reference.md, doc/index.md, src/Images.jl, src/algorithms.jl, src/connected.jl, src/core.jl, src/map.jl, src/overlays.jl, src/writemime.jl, test/algorithms.jl, test/core.jl, test/map.jl, test/overlays.jl, test/runtests.jl, test/writemime.jl
This merges #387 with some of my own changes, especially fixes for broken tests.
=> Update to current UFixed

src/algorithms.jl
Here is a (perhaps too simplistic) « fix ».
=> "Don't pad in imfilter_fft if size(kernel)==size(img)"

.travis.yml, appveyor.yml, test/algorithms.jl
=> Add tests for circular filtering

src/algorithms.jl, test/algorithms.jl
@timholy Please let me know if I rebased/squashed correctly, and if there's anything else to change.
=> added test_approx_eq_sigma_eps function and difftype fix

doc/function_reference.md, src/Images.jl, src/corner.jl, test/corner.jl, test/runtests.jl
This adds corner detection based on the Harris algorithm and the Shi-Tomasi algorithm. These are pretty common image processing tasks, so I thought they may be useful to others.
=> Add corner detection functionality

src/core.jl, test/core.jl
Adds support for sub/slice creation with Vector{Int}, uses Base for Colon indexing.
=> Support the same indexing semantics as general AbstractArrays

src/algorithms.jl, test/algorithms.jl
Changes to FixedPointNumbers triggered the bug.
CC @cstjean.
=> Prevent overflow in restrict. Fixes #395.

src/Images.jl, src/algorithms.jl, test/algorithms.jl
Added function and tests for 2d and 4d case
=> Add extrema_filter

src/algorithms.jl, src/core.jl, test/core.jl
This also fixes a potential overwriting of original data with `imfilter_gaussian`.
=> Fix properties when using sliceim with Colons

src/edge.jl
Just a small fix. Can the author please review and see if this is what they intended?
=> typo fix in sample code

src/writemime.jl, test/REQUIRE, test/writemime.jl
A redo of #445, as GitHub closed the issue due to a commit to Colors that referenced the PR in Images.
=> Rework writemime, take 2

src/algorithms.jl, test/algorithms.jl
=> Support imcomplement for color/transparent images. Fixes #461.

docs/src/function_reference.md, src/Images.jl, src/algorithms.jl, test/algorithms.jl
might be a better place to put feature extraction algorithms in future as discussed in https://github.com/timholy/Images.jl/issues/453 and https://github.com/seung-lab/ImageRegistration.jl/issues/2, but thought i'd submit a PR for this blob detector i recently made before @mronian gets to work
=> added blob_LoG

src/algorithms.jl, src/core.jl, src/map.jl, test/edge.jl
This eliminates a lot of warnings, as well as a few bugs. Likely to require https://github.com/JuliaLang/julia/pull/15810 (UPDATE: more importantly, the part moved to https://github.com/JuliaLang/julia/pull/15814), but let's try it anyway.
=> Fixes for julia-0.5

src/algorithms.jl, test/algorithms.jl, test/map.jl
see discussion here:  https://github.com/timholy/Images.jl/issues/470
=> remove duplicate code for imadjustintensity

src/Images.jl, src/core.jl, src/map.jl, test/core.jl
Fixes for ambiguity warnings, changes in scope, and new support/fixes for `reshape`.
=> Some julia-0.5 updates

REQUIRE, docs/src/core.md, src/Images.jl, src/algorithms.jl, src/connected.jl, src/core.jl, src/map.jl, src/overlays.jl, test/core.jl, test/map.jl, test/overlays.jl
`ImageMagick.jl` PR coming soon. The only depwarn left comes from base https://github.com/JuliaLang/julia/pull/15675#issuecomment-214703355
=> Fix depwarn on 0.5

docs/src/function_reference.md
See https://github.com/MichaelHatherly/Documenter.jl/pull/51 for details.
=> Updates for Documenter.jl syntax changes

docs/src/function_reference.md, src/Images.jl, src/edge.jl, test/edge.jl
Based on @siddhantjain's version in #441. Adds thresholding of weak edges using BFS.
=> Adds Canny Edge Detection

src/Images.jl, src/core.jl, test/core.jl
Hopefully this will fix our tests (and Travis).
=> Fix for sub/slice->view

docs/src/function_reference.md, src/Images.jl, src/algorithms.jl, test/algorithms.jl
=> Adds Histogram Matching

src/map.jl, src/writemime.jl
I'm not certain this will pass CI because it's a simultaneous change to both this package and ImageMagick, but locally the two together pass on both 0.4 and 0.5. CC @mronian, @bjarthur
=> Some fixes for writemime

docs/src/function_reference.md, src/Images.jl, src/algorithms.jl, src/corner.jl, test/corner.jl
1. Support for Other ColorTypes
2. Thresholding
3. Kitchen Rosenfeld Corner Detection
4. Gamma Weighted Covariance Matrices
I had a discussion with @SimonDanisch who suggested using function names as arguments to decide which method to select. @timholy He asked me to take your advice before implementing this in other cases.
=> Updates imcorner and makes it modular, adds new features.

src/corner.jl, test/corner.jl
Adds Fast Corner detection with High Speed Test for n>=12.
Needs #498 to be merged first.
=> Adds FAST Corner Detection.

docs/src/function_reference.md, src/Images.jl
=> Exports FAST, adds to function reference.

src/algorithms.jl, test/algorithms.jl
=> Fix dispatch for padarray with SubArrays. Fixes #525

src/Images.jl, src/algorithms.jl, src/exposure.jl, test/exposure.jl
Needs #514.
How should we handle colour images? [Refer https://github.com/timholy/Images.jl/pull/516#discussion_r71996858]
=> Adds Contrast Limited Adaptive Histogram Equalisation(CLAHE)

src/exposure.jl
Ref https://github.com/timholy/Images.jl/pull/523#issuecomment-235236460, CC @mronian.
=> Faster histeq

docs/src/function_reference.md, src/exposure.jl
Missed the docs while shifting to exposure.jl.
=> Fixes Docs

docs/src/function_reference.md, src/Images.jl, src/algorithms.jl, test/algorithms.jl
Makes things easier in ImageFeatures.jl.
=> Adds Integral Window Sum

src/algorithms.jl
Refer https://github.com/timholy/Images.jl/commit/4cd185c5d977dc0632239f9f62ca779f358f0640#commitcomment-18546910
=> Fix Version checking for chkbounds

src/algorithms.jl
Small changes I had locally done while working on ORB but forgot to push to this PR.
=> fix gaussianpyramid

.travis.yml, appveyor.yml, src/algorithms.jl, src/corner.jl, src/edge.jl, test/algorithms.jl, test/edge.jl
Ref. https://groups.google.com/d/msg/julia-users/NrSr8IndWAw/l5ezvy-sBgAJ.
CC @bjarthur, hope this is OK. I noticed your test used a triangle-shaped sigma, perhaps not unrelated? If you disagree with this, then we should at least document the issue.
=> blob_LoG: don't discard edges in the "sigma" dimension

src/writemime.jl
Not sure why this was commented out originally.
=> Display AbstractMatrix{Colorant} in IJulia (fixes #548)

src/writemime.jl, test/writemime.jl
This should fix the last part of #548. CC @tlnagy.
=> Turn off Colors' svg display of color matrices (fixes #548)

test/algorithms.jl, test/map.jl, test/overlays.jl
Fixes needed because of:
https://github.com/JuliaGraphics/ColorTypes.jl/pull/56
https://github.com/JuliaMath/FixedPointNumbers.jl/pull/59
=> Fixes for recent deprecations/changes in ColorTypes/FixedPointNumbers

src/map.jl
This is cherry-picked from `images-next`.
=> Some fixes to avoid warnings from RGB24/UInt32 convert->reinterpret deprecation

test/REQUIRE
Might as well wait for the QuartzImageIO tag 
JuliaLang/METADATA.jl#7814
=> Update test REQUIRE

.travis.yml, README.md
Let's get those badges green again!
=> Allow nightly failures, add codecov

REQUIRE
https://github.com/JuliaLang/METADATA.jl/pull/8502#discussion_r108064972
=> Bump Compat version

src/Images.jl, src/deprecated.jl, src/edge.jl, test/edge.jl
The second commit here makes small tweaks to #607 in the docstrings and depwarns.
=> Canny revamp (small tweaks to #607)

test/runtests.jl
Makes it easier to see all test results in one view.
=> Wrap tests in one master testset

src/algorithms.jl, test/algorithms.jl
=> Fix range construction in restrict. Fixes #655

src/Images.jl, src/algorithms.jl, test/algorithms.jl
Yen's auto thresholding algorithm as discussed in this paper [Yen J.C., Chang F.J., and Chang S. (1995) “A New Criterion for Automatic Multilevel Thresholding”](http://ieeexplore.ieee.org/document/366472/)
=> Added Yen's auto thresholding algorithm

src/Images.jl, src/algorithms.jl, test/algorithms.jl
@zygmuntszpak @Evizero I have added the clearborder function that clears object that are connected to the border of the image.
=> Added clearborder function

REQUIRE, src/Images.jl, src/algorithms.jl, test/algorithms.jl
=> Adds OffsetArrays capability to gaussian_pyramid

NEWS.md, REQUIRE
Small updates in order to tag the latest master.
Note that we already skipped documenting a bunch of tags in NEWS.md (I am sure much of which is my oversight). We should try to pay more attention to this before merging PRs.
=> update NEWS.md and REQUIRE

src/algorithms.jl, src/showmime.jl
This should get the MIME show stuff working for IJulia and fixes a test.
=> a couple of last minute fixes for Julia v0.7

src/algorithms.jl
Its used later in this file and I get a deprecation warning in my code.
=> Using Statistics.var

src/Images.jl
Closes: https://github.com/JuliaImages/Images.jl/issues/697
=> removed undefined exports

README.md
close https://github.com/JuliaImages/Images.jl/issues/794
=> replace gitter with slack

.gitignore, .travis.yml, Project.toml, appveyor.yml, test/exposure.jl
We seem to be failing tests, this should fix it.
=> Improve eltype generality in imstretch test

README.md
=> add stargazers over time chart

src/bwdist.jl
This is purely cosmetic, but it increases the similarity to the pseudocode in the paper.
(I'm using this as an example of Julia's advantages in a grant application. See also https://discourse.julialang.org/t/in-as-few-lines-as-possible-describe-why-you-love-julia/33179/16)
=> Notation/naming tweaks to computeft!

Project.toml
=> Support OffsetArrays 1.x

CONTRIBUTING.md, LICENSE.md, README.md
It seems this might help newcomers. I wasn't sure exactly where to host it, but this seems to be as good as any. We could also put it in the juliaimages docs, or at least put a link there to this repo.
=> Add a CONTRIBUTING.md file

README.md
=> Minor correction to previous commit.

src/corner.jl
The docstring of imcorner seems to be outdated as of #617 , here's a quick fix.
English is not my first language so I don't doubt that sentence could be made a bit clearer.
=> Update docstring for imcorner

src/algorithms.jl, src/deprecations.jl, test/algorithms.jl
Other PRs require this patch, so I'll merge as long as the test passes.
=> [patch] upgrade codebase wrt ColorVectorSpace 0.9

test/writemime.jl
https://github.com/JuliaIO/ImageMagick.jl/pull/111 might have to be merged and tag for this to pass tests.
=> add support for FileIO's new metadata method
